### PR TITLE
Completed the UML Activity Diagram for User Story 1. Wrote out the ba…

### PR DESCRIPTION
**Pull request by JonasonWu**
…seline for placement of User Story 2.

### CODE REVIEW

**Review by sagynbek001 — CHANGES_REQUESTED** [review]
There are a few points I want you to reconsider:
 
* I believe the start and end circles must be a bit different, the end has to have one more layer of a circle around it.
* The vertices of the rectangles are curved in the Activity Diagram.
* Rectangles' text is not page names, but rather actions, so they should start with a verb.

Otherwise, LGTM!

**Comment by sagynbek001** [comment]
Shouldn't we use rounded corner rectangles for Activity Diagrams?

**Comment by JonasonWu** [comment]
Got it. Changing it now

**Comment by JonasonWu** [comment]
Finished changing to rounded rectangles

**Review by sagynbek001 — APPROVED** [review]
LGTM!

**Pull request merged**
